"""
Create Downtime Reason Custom DocType and load initial data from M_DT.pdf.
Run with: bench --site erp.qcstyro.local execute qcmc_logic.setup_downtime_reason.run
"""
import frappe


def run():
    _create_doctype()
    _insert_records()
    frappe.db.commit()
    frappe.clear_cache(doctype="Downtime Reason")
    total = frappe.db.count("Downtime Reason")
    print(f"Done. {total} Downtime Reason records in database.")


# ---------------------------------------------------------------------------
# DocType creation
# ---------------------------------------------------------------------------

def _create_doctype():
    if frappe.db.exists("DocType", "Downtime Reason"):
        print("DocType 'Downtime Reason' already exists — skipping creation.")
        return

    dt = frappe.get_doc({
        "doctype": "DocType",
        "name": "Downtime Reason",
        "module": "QCMC Logics",
        "custom": 1,
        "autoname": "field:dt_code",
        "is_submittable": 0,
        "track_changes": 0,
        "fields": [
            {
                "fieldname": "dt_code",
                "label": "DT Code",
                "fieldtype": "Data",
                "reqd": 1,
                "unique": 1,
                "in_list_view": 1,
                "columns": 1,
            },
            {
                "fieldname": "description",
                "label": "Description",
                "fieldtype": "Data",
                "reqd": 1,
                "in_list_view": 1,
                "in_global_search": 1,
                "columns": 4,
            },
            {
                "fieldname": "category",
                "label": "Category",
                "fieldtype": "Select",
                "options": "\nPROD-DT\nPROD-UNPLANNED\nBD\nVOS-UNPLANNED",
                "reqd": 1,
                "in_list_view": 1,
                "in_standard_filter": 1,
                "columns": 2,
            },
            {
                "fieldname": "subcategory",
                "label": "Sub-Category",
                "fieldtype": "Data",
                "in_list_view": 1,
                "in_standard_filter": 1,
                "columns": 2,
            },
            {
                "fieldname": "plant",
                "label": "Plant",
                "fieldtype": "Select",
                "options": "\nMC\nQC",
                "in_list_view": 1,
                "in_standard_filter": 1,
                "columns": 1,
            },
            {
                "fieldname": "is_active",
                "label": "Is Active",
                "fieldtype": "Check",
                "default": "1",
                "in_list_view": 1,
                "columns": 1,
            },
        ],
        "permissions": [
            {
                "role": "System Manager",
                "permlevel": 0,
                "read": 1, "write": 1, "create": 1, "delete": 1,
                "print": 1, "email": 1, "report": 1, "export": 1,
            },
            {
                "role": "All",
                "permlevel": 0,
                "read": 1,
            },
        ],
    })
    dt.insert(ignore_permissions=True)
    print("DocType 'Downtime Reason' created.")


# ---------------------------------------------------------------------------
# Seed data — parsed from M_DT.pdf
# Columns: (dt_code, description, category, subcategory, plant)
# Row 288 skipped (all NULL values)
# ---------------------------------------------------------------------------

RECORDS = [
    ("15",  "Alignment",                                     "PROD-DT",        "MOLD",             "MC"),
    ("16",  "Minor Repair",                                  "PROD-DT",        "MOLD",             "MC"),
    ("17",  "Cooling System",                                "PROD-DT",        "MOLD",             "MC"),
    ("18",  "Polishing",                                     "PROD-DT",        "MOLD",             "MC"),
    ("20",  "New / Trainee / Transfer to Other Operation",   "PROD-DT",        "MANPOWER",         "MC"),
    ("21",  "Skills",                                        "PROD-DT",        "MANPOWER",         "MC"),
    ("22",  "Lack of Manpower / Absenteeism",                "PROD-DT",        "MANPOWER",         "MC"),
    ("23",  "Delay",                                         "PROD-DT",        "MATERIAL",         "MC"),
    ("24",  "Reject",                                        "PROD-DT",        "MATERIAL",         "MC"),
    ("25",  "Under / Over Age Material",                     "PROD-DT",        "MATERIAL",         "MC"),
    ("26",  "SOP's",                                         "PROD-DT",        "METHOD",           "MC"),
    ("27",  "Deviated",                                      "PROD-DT",        "METHOD",           "MC"),
    ("28",  "Product Change Over",                           "PROD-UNPLANNED", "PRODUCTION",       "MC"),
    ("29",  "Stabilization After Change Over",               "PROD-UNPLANNED", "PRODUCTION",       "MC"),
    ("30",  "HR Activities / Monthly Meeting",               "PROD-UNPLANNED", "PRODUCTION",       "MC"),
    ("31",  "Planned Audit",                                 "PROD-UNPLANNED", "PRODUCTION",       "MC"),
    ("32",  "Start-up After Declared NPO",                   "PROD-UNPLANNED", "PRODUCTION",       "MC"),
    ("33",  "No Materials",                                  "PROD-UNPLANNED", "PURCHASING",       "MC"),
    ("34",  "No Parts Availability",                         "PROD-UNPLANNED", "PURCHASING",       "MC"),
    ("35",  "Wrong Parts",                                   "PROD-UNPLANNED", "PURCHASING",       "MC"),
    ("36",  "Mold Repair",                                   "PROD-UNPLANNED", "ENGINEERING",      "MC"),
    ("37",  "Back Jobs - Machining / Fabrication Works",     "PROD-UNPLANNED", "ENGINEERING",      "MC"),
    ("38",  "Roll Quality and Specs",                        "PROD-UNPLANNED", "MC PLANT",         "MC"),
    ("39",  "Late Delivery",                                 "PROD-UNPLANNED", "MC PLANT",         "MC"),
    ("40",  "Un Planned Schedule",                           "PROD-UNPLANNED", "PPIC",             "MC"),
    ("41",  "Pending Requested Manpower",                    "PROD-UNPLANNED", "HR",               "MC"),
    ("42",  "Absenteeism",                                   "PROD-UNPLANNED", "HR",               "MC"),
    ("44",  "Loader Under Repair",                           "PROD-UNPLANNED", "POWER PLANT",      "MC"),
    ("47",  "Maintenance",                                   "PROD-UNPLANNED", "POWER PLANT",      "MC"),
    ("48",  "No Electricity",                                "PROD-UNPLANNED", "EXTERNAL FACTORS", "MC"),
    ("49",  "Transformer Problem - Line Side",               "PROD-UNPLANNED", "EXTERNAL FACTORS", "MC"),
    ("50",  "Typhoon / Floods",                              "PROD-UNPLANNED", "EXTERNAL FACTORS", "MC"),
    ("51",  "Earthquake / Fire",                             "PROD-UNPLANNED", "EXTERNAL FACTORS", "MC"),
    ("52",  "Auxiliaries Problem",                           "PROD-DT",        "AUXILIARIES",      "MC"),
    ("53",  "Stabilization After Repair",                    "PROD-UNPLANNED", "PRODUCTION",       "MC"),
    ("54",  "Production Downtime - MC",                      "PROD-UNPLANNED", "PRODUCTION",       "MC"),
    ("55",  "Low Steam Supply",                              "PROD-DT",        "BOILER",           "QC"),
    ("56",  "Low Air",                                       "PROD-DT",        "AUXILIARIES",      "QC"),
    ("57",  "Low Cooling Pressure",                          "PROD-DT",        "AUXILIARIES",      "QC"),
    ("58",  "Low Cooling Temperature",                       "PROD-DT",        "AUXILIARIES",      "QC"),
    ("59",  "Downtime Electrical Problem Machine (1)",       "PROD-DT",        "AUXILIARIES",      "QC"),
    ("60",  "Downtime Electrical Problem Machine (2)",       "PROD-DT",        "AUXILIARIES",      "QC"),
    ("61",  "No Loader Available / No Driver",               "PROD-DT",        "AUXILIARIES",      "QC"),
    ("62",  "Low Water Level",                               "PROD-DT",        "AUXILIARIES",      "QC"),
    ("63",  "Central Vacuum System",                         "PROD-DT",        "AUXILIARIES",      "QC"),
    ("64",  "Low Gas Pressure - Plant 33",                   "PROD-DT",        "AUXILIARIES",      "QC"),
    ("65",  "Chiller - High Cooling Temperature",            "PROD-DT",        "AUXILIARIES",      "QC"),
    ("66",  "Water Treatment Facilities - Steam",            "PROD-DT",        "AUXILIARIES",      "QC"),
    ("67",  "Mold Alignment",                                "PROD-DT",        "MOULD",            "QC"),
    ("69",  "Steam Inlet Replacement / or Repair",           "PROD-DT",        "MOULD",            "QC"),
    ("70",  "Mold Polishing / Cleaning and Maintenance",     "PROD-DT",        "MOULD",            "QC"),
    ("71",  "Mold - O-Ring Replacement",                     "PROD-DT",        "MOULD",            "QC"),
    ("72",  "Feeding Gun Replacement or Repair",             "PROD-DT",        "MOULD",            "QC"),
    ("73",  "Push Rod Repair or Replace",                    "PROD-DT",        "MOULD",            "QC"),
    ("74",  "Inject Plate Repair",                           "PROD-DT",        "MOULD",            "QC"),
    ("75",  "Mold Cutter Repair",                            "PROD-DT",        "MOULD",            "QC"),
    ("76",  "Mold Cutter Re-Sharpening",                     "PROD-DT",        "MOULD",            "QC"),
    ("77",  "Plug Assists Polishing",                        "PROD-DT",        "MOULD",            "QC"),
    ("78",  "Mold Insert Repair",                            "PROD-DT",        "MOULD",            "QC"),
    ("79",  "Push Plate Repair",                             "PROD-DT",        "MOULD",            "QC"),
    ("80",  "Material Hose and Fittings",                    "PROD-DT",        "MOULD",            "QC"),
    ("81",  "Air Hose Fitting",                              "PROD-DT",        "MOULD",            "QC"),
    ("82",  "Steam Hose and Clamp",                          "PROD-DT",        "MOULD",            "QC"),
    ("83",  "Mold Cooling System",                           "PROD-DT",        "MOULD",            "QC"),
    ("84",  "Mold Puncher Repair - PSP",                     "PROD-DT",        "MOULD",            "QC"),
    ("85",  "Mold Bender Repair - PSP",                      "PROD-DT",        "MOULD",            "QC"),
    ("86",  "Mold Blade Replacement",                        "PROD-DT",        "MOULD",            "QC"),
    ("87",  "Machine Slowdown - New / Trainee",              "PROD-DT",        "MANPOWER",         "QC"),
    ("88",  "Lack of Manpower / Absenteeism",                "PROD-DT",        "MANPOWER",         "QC"),
    ("89",  "Delay - Material Preparation",                  "PROD-DT",        "MATERIAL",         "QC"),
    ("90",  "Delay - Issuance and Delivery (Raw Material)",  "PROD-DT",        "MATERIAL",         "QC"),
    ("91",  "Delay - Issuance and Delivery (Finished Goods)","PROD-DT",        "MATERIAL",         "QC"),
    ("92",  "Deviated Raw Material",                         "PROD-DT",        "MATERIAL",         "QC"),
    ("93",  "Material Under / Over Age",                     "PROD-DT",        "MATERIAL",         "QC"),
    ("94",  "Parameter Adjustment - Due to Material Issue",  "PROD-DT",        "METHOD",           "QC"),
    ("95",  "Parameter Adjustment - Due to Machine",         "PROD-DT",        "METHOD",           "QC"),
    ("96",  "Parameter Adjustment - Due to Mould",           "PROD-DT",        "METHOD",           "QC"),
    ("97",  "Parameter Adjustment - Due to Operator",        "PROD-DT",        "METHOD",           "QC"),
    ("98",  "Parameter Adjustment - Due to Quality",         "PROD-DT",        "METHOD",           "QC"),
    ("99",  "Parameter Adjustment - Weight",                 "PROD-DT",        "METHOD",           "QC"),
    ("100", "Deviated Quality Compliance",                   "PROD-DT",        "METHOD",           "QC"),
    ("110", "Product Change Over - Unplanned",               "VOS-UNPLANNED",  "METHOD",           "QC"),
    ("111", "Stabilization After Change Over",               "VOS-UNPLANNED",  "METHOD",           "QC"),
    ("112", "Scheduled General Assembly Meeting",            "VOS-UNPLANNED",  "METHOD",           "QC"),
    ("113", "Start-up Operation - Prolonged Startup",        "VOS-UNPLANNED",  "METHOD",           "QC"),
    ("114", "JOC Advance vs Scheduled Production",           "VOS-UNPLANNED",  "METHOD",           "QC"),
    ("117", "Stabilization After Machine Repair",            "PROD-DT",        "METHOD",           "MC"),
    ("118", "Selected Run Due to Boiler Problem",            "VOS-UNPLANNED",  "METHOD",           "QC"),
    ("122", "Material Testing",                              "PROD-DT",        "METHOD",           "QC"),
    ("125", "Parameter Adjustment - Red Tag",                "PROD-DT",        "METHOD",           "QC"),
    ("126", "Parameter Adjustment - Changeover",             "PROD-DT",        "METHOD",           "QC"),
    ("127", "Material Stuck Up @ Conveyor",                  "PROD-DT",        "METHOD",           "QC"),
    ("128", "Parameter Adjustment - Heater",                 "PROD-DT",        "METHOD",           "QC"),
    ("129", "Offset Cutting",                                "PROD-DT",        "METHOD",           "QC"),
    ("131", "Screen Problem",                                "PROD-UNPLANNED", "MANPOWER",         "MC"),
    ("132", "BGE/Extruder and Roller Assembly",              "BD",             "MACHINE",          "QC"),
    ("133", "Chamber Assembly",                              "BD",             "MACHINE",          "QC"),
    ("134", "Cutter Assembly",                               "BD",             "MACHINE",          "QC"),
    ("135", "Cylinder Assemblies",                           "BD",             "MACHINE",          "QC"),
    ("136", "Drive Trains Assemblies",                       "BD",             "MACHINE",          "QC"),
    ("137", "Electrical/Electronics",                        "BD",             "MACHINE",          "QC"),
    ("139", "Hydraulic Assemblies",                          "BD",             "MACHINE",          "QC"),
    ("140", "Machine Steam Distributor",                     "BD",             "MACHINE",          "QC"),
    ("141", "Machine Steam Driver Distributor",              "BD",             "MACHINE",          "QC"),
    ("142", "Material Handling Assembly",                    "BD",             "MACHINE",          "QC"),
    ("143", "Other Mechanical Works",                        "BD",             "MACHINE",          "QC"),
    ("144", "Pneumatic Assemblies",                          "BD",             "MACHINE",          "QC"),
    ("145", "Product Handling Assembly",                     "BD",             "MACHINE",          "QC"),
    ("146", "Swivel Arm Assembly",                           "BD",             "MACHINE",          "QC"),
    ("216", "Air End",                                       "BD",             "MACHINE",          "MC"),
    ("217", "Air Filter",                                    "BD",             "MACHINE",          "MC"),
    ("218", "Air Inlet System",                              "BD",             "MACHINE",          "MC"),
    ("219", "Air/Water Leak",                                "BD",             "MACHINE",          "MC"),
    ("220", "Arm Bushings",                                  "BD",             "MACHINE",          "MC"),
    ("221", "Autoloader",                                    "BD",             "MACHINE",          "MC"),
    ("222", "Barrel Heater",                                 "BD",             "MACHINE",          "MC"),
    ("223", "Bearing",                                       "BD",             "MACHINE",          "MC"),
    ("224", "Blade",                                         "BD",             "MACHINE",          "MC"),
    ("225", "Blower",                                        "BD",             "MACHINE",          "MC"),
    ("226", "Brake",                                         "BD",             "MACHINE",          "MC"),
    ("227", "Chiller",                                       "BD",             "MACHINE",          "MC"),
    ("228", "Color Head",                                    "BD",             "MACHINE",          "MC"),
    ("229", "Compactor",                                     "BD",             "MACHINE",          "MC"),
    ("230", "Compressor",                                    "BD",             "MACHINE",          "MC"),
    ("231", "Condenser Pump",                                "BD",             "MACHINE",          "MC"),
    ("232", "Control",                                       "BD",             "MACHINE",          "MC"),
    ("233", "Conveyor",                                      "BD",             "MACHINE",          "MC"),
    ("234", "Cooling",                                       "BD",             "MACHINE",          "MC"),
    ("235", "Corona",                                        "BD",             "MACHINE",          "MC"),
    ("236", "Cross Joint",                                   "BD",             "MACHINE",          "MC"),
    ("237", "Cutter",                                        "BD",             "MACHINE",          "MC"),
    ("238", "DC Control",                                    "BD",             "MACHINE",          "MC"),
    ("239", "Downholder",                                    "BD",             "MACHINE",          "MC"),
    ("240", "Ejector",                                       "BD",             "MACHINE",          "MC"),
    ("241", "Electrical Wirings",                            "BD",             "MACHINE",          "MC"),
    ("242", "Electronic",                                    "BD",             "MACHINE",          "MC"),
    ("243", "Evaporator Pump",                               "BD",             "MACHINE",          "MC"),
    ("244", "Feeder",                                        "BD",             "MACHINE",          "MC"),
    ("245", "Feedlength",                                    "BD",             "MACHINE",          "MC"),
    ("246", "Forming",                                       "BD",             "MACHINE",          "MC"),
    ("247", "Gearbox",                                       "BD",             "MACHINE",          "MC"),
    ("248", "Heater",                                        "BD",             "MACHINE",          "MC"),
    ("249", "Hydraulic Cylinder",                            "BD",             "MACHINE",          "MC"),
    ("250", "Hydraulic Pump",                                "BD",             "MACHINE",          "MC"),
    ("251", "Hydraulic Valve",                               "BD",             "MACHINE",          "MC"),
    ("252", "Inverter",                                      "BD",             "MACHINE",          "MC"),
    ("254", "Mandrel",                                       "BD",             "MACHINE",          "MC"),
    ("256", "Motor Winding",                                 "BD",             "MACHINE",          "MC"),
    ("257", "Oil Filter",                                    "BD",             "MACHINE",          "MC"),
    ("258", "PLC",                                           "BD",             "MACHINE",          "MC"),
    ("259", "Plug Assist",                                   "BD",             "MACHINE",          "MC"),
    ("260", "Pneumatic Cylinder",                            "BD",             "MACHINE",          "MC"),
    ("261", "Pneumatic Valve",                               "BD",             "MACHINE",          "MC"),
    ("263", "Robot",                                         "BD",             "MACHINE",          "MC"),
    ("265", "Rotary Union",                                  "BD",             "MACHINE",          "MC"),
    ("266", "Scrap Winder",                                  "BD",             "MACHINE",          "MC"),
    ("267", "Screw Feeder",                                  "BD",             "MACHINE",          "MC"),
    ("268", "Sensor",                                        "BD",             "MACHINE",          "MC"),
    ("269", "Separator Element",                             "BD",             "MACHINE",          "MC"),
    ("270", "Servo Control",                                 "BD",             "MACHINE",          "MC"),
    ("271", "Servo Drive",                                   "BD",             "MACHINE",          "MC"),
    ("272", "Shutter",                                       "BD",             "MACHINE",          "MC"),
    ("273", "Smoothing Roll",                                "BD",             "MACHINE",          "MC"),
    ("274", "Spreading Device",                              "BD",             "MACHINE",          "MC"),
    ("275", "Stacker",                                       "BD",             "MACHINE",          "MC"),
    ("276", "Take-Off",                                      "BD",             "MACHINE",          "MC"),
    ("277", "Thermo Controller",                             "BD",             "MACHINE",          "MC"),
    ("278", "Transport",                                     "BD",             "MACHINE",          "MC"),
    ("280", "Unreeling",                                     "BD",             "MACHINE",          "MC"),
    ("281", "UV Lamp",                                       "BD",             "MACHINE",          "MC"),
    ("282", "V-Belt",                                        "BD",             "MACHINE",          "MC"),
    ("283", "Vacuum",                                        "BD",             "MACHINE",          "MC"),
    ("284", "Winder",                                        "BD",             "MACHINE",          "MC"),
    ("285", "Low Air (Compressor)",                          "PROD-DT",        "COMPRESSOR",       "QC"),
    ("286", "Purging",                                       "PROD-DT",        "METHOD",           "QC"),
    ("289", "Spring Loaded Valve",                           "BD",             "MACHINE",          "QC"),
    ("290", "Steam Diaphragm Problem",                       "BD",             "MACHINE",          "QC"),
    ("291", "Heater Malfunction",                            "BD",             "MACHINE",          "QC"),
    ("292", "Steam Fix Malfunction",                         "BD",             "MACHINE",          "QC"),
    ("293", "Vacuum Motor Problem",                          "BD",             "MACHINE",          "QC"),
    ("294", "Steam Mobile Problem",                          "BD",             "MACHINE",          "QC"),
    ("295", "Fill Crack Problem",                            "BD",             "MACHINE",          "QC"),
    ("296", "Control Malfunction",                           "BD",             "MACHINE",          "QC"),
    ("297", "Sensor Malfunction",                            "BD",             "MACHINE",          "QC"),
    ("298", "Drain Valve Problem",                           "BD",             "MACHINE",          "QC"),
    ("299", "Pilot Valve Problem",                           "BD",             "MACHINE",          "QC"),
    ("300", "Solenoid Problem",                              "BD",             "MACHINE",          "QC"),
    ("301", "Cooling Shower Problem",                        "BD",             "MACHINE",          "QC"),
    ("302", "Die Head Repair",                               "BD",             "MACHINE",          "QC"),
    ("303", "Length Sensor Problem",                         "BD",             "MACHINE",          "QC"),
    ("304", "Steam Hose Problem",                            "BD",             "MACHINE",          "QC"),
    ("305", "Steam Leak Problem",                            "BD",             "MOULD",            "QC"),
    ("306", "Mould Cavity Problem",                          "PROD-DT",        "MOULD",            "QC"),
    ("307", "Other Mechanical Works (MC)",                   "BD",             "MACHINE",          "MC"),
    ("308", "Cooling Problem",                               "BD",             "MACHINE",          "QC"),
    ("309", "Shafting",                                      "BD",             "MACHINE",          "MC"),
    ("310", "Pinshaft",                                      "BD",             "MACHINE",          "MC"),
    ("311", "Relay",                                         "BD",             "MACHINE",          "MC"),
    ("312", "Roller Feeder Malfunction",                     "BD",             "MACHINE",          "MC"),
    ("314", "Air Blow Malfunction",                          "BD",             "MACHINE",          "MC"),
    ("316", "Encoder Malfunction",                           "BD",             "MACHINE",          "MC"),
    ("317", "Die Head",                                      "BD",             "MACHINE",          "MC"),
    ("322", "Cutting Alignment",                             "BD",             "MACHINE",          "MC"),
    ("323", "Broken Spring",                                 "BD",             "MACHINE",          "MC"),
    ("330", "Cylinder",                                      "BD",             "MACHINE",          "MC"),
    ("333", "Pelletizing Head",                              "BD",             "MACHINE",          "MC"),
    ("334", "Camfollower",                                   "BD",             "MACHINE",          "MC"),
    ("335", "Rubber Pad",                                    "BD",             "MACHINE",          "MC"),
    ("338", "Maindrive Chain",                               "BD",             "MACHINE",          "MC"),
    ("339", "Water Pump Hose Water Leak",                    "BD",             "MACHINE",          "MC"),
    ("340", "Middle Roller Malfunction",                     "BD",             "MACHINE",          "MC"),
    ("341", "Granulator Motor Malfunction",                  "BD",             "MACHINE",          "MC"),
    ("342", "Conveyor Problem",                              "BD",             "MACHINE",          "QC"),
    ("343", "Delay Change Mould",                            "PROD-DT",        "MOULD",            "QC"),
    ("345", "Drying Time",                                   "PROD-DT",        "METHOD",           "QC"),
    ("346", "Granulator Problem",                            "BD",             "MACHINE",          "QC"),
    ("347", "Change Material",                               "PROD-DT",        "MATERIAL",         "QC"),
    ("348", "Cart Limitation / Cart Delay",                  "PROD-DT",        "METHOD",           "QC"),
    ("349", "Black Spot",                                    "PROD-DT",        "MATERIAL",         "MC"),
    ("350", "Fish Eye",                                      "PROD-DT",        "MATERIAL",         "MC"),
    ("351", "Gear Pump",                                     "BD",             "MACHINE",          "MC"),
    ("352", "Hopper",                                        "BD",             "MACHINE",          "MC"),
    ("353", "Low Pressure",                                  "PROD-DT",        "MATERIAL",         "MC"),
    ("354", "Maindrive Motor",                               "BD",             "MACHINE",          "MC"),
    ("355", "Pump Motor",                                    "BD",             "MACHINE",          "MC"),
    ("356", "Upper Roller",                                  "BD",             "MACHINE",          "MC"),
    ("357", "Lower Roller",                                  "BD",             "MACHINE",          "MC"),
    ("358", "Screen Changer",                                "BD",             "MACHINE",          "MC"),
    ("359", "Strainer",                                      "BD",             "MACHINE",          "MC"),
    ("360", "Take Off Malfunction",                          "BD",             "MACHINE",          "MC"),
    ("361", "Throttle",                                      "BD",             "MACHINE",          "MC"),
    ("362", "Vacuum Motor",                                  "BD",             "MACHINE",          "MC"),
    ("363", "Water Pipe",                                    "BD",             "MACHINE",          "MC"),
    ("364", "Wet Pellets",                                   "PROD-DT",        "MATERIAL",         "MC"),
    ("365", "White Marks",                                   "PROD-DT",        "MATERIAL",         "MC"),
    ("366", "Blanking Press",                                "BD",             "MACHINE",          "MC"),
    ("367", "Buldging Problem",                              "PROD-DT",        "MATERIAL",         "MC"),
    ("368", "Bulutong Problem",                              "PROD-DT",        "MATERIAL",         "MC"),
    ("370", "Auto Start Malfunction",                        "BD",             "MACHINE",          "MC"),
    ("371", "Auto Stop Malfunction",                         "BD",             "MACHINE",          "MC"),
    ("372", "Manual Mode Malfunction",                       "BD",             "MACHINE",          "MC"),
    ("373", "Crumpled Problem",                              "BD",             "MACHINE",          "MC"),
    ("374", "Cutting Cylinder",                              "BD",             "MACHINE",          "MC"),
    ("375", "Cutting Adjuster",                              "BD",             "MACHINE",          "MC"),
    ("376", "Ejector Cylinder",                              "BD",             "MACHINE",          "MC"),
    ("378", "Flashing",                                      "PROD-DT",        "METHOD",           "MC"),
    ("379", "Horse Shoe",                                    "BD",             "MACHINE",          "MC"),
    ("380", "Hydraulic Motor",                               "BD",             "MACHINE",          "MC"),
    ("381", "Hydraulic Leak",                                "BD",             "MACHINE",          "MC"),
    ("382", "Inline Grinder Problem",                        "BD",             "MACHINE",          "MC"),
    ("383", "Insert Problem",                                "BD",             "MACHINE",          "MC"),
    ("384", "Lower Table",                                   "BD",             "MACHINE",          "MC"),
    ("385", "Material Sag (Material)",                       "PROD-DT",        "MATERIAL",         "MC"),
    ("387", "Guide Post",                                    "BD",             "MACHINE",          "MC"),
    ("388", "Junction Holder",                               "BD",             "MACHINE",          "MC"),
    ("389", "Bolt Problem (Loose)",                          "BD",             "MACHINE",          "MC"),
    ("390", "Mechanical Arm",                                "BD",             "MACHINE",          "MC"),
    ("391", "Mould Center Post",                             "BD",             "MACHINE",          "MC"),
    ("392", "Offset Problem",                                "PROD-DT",        "METHOD",           "MC"),
    ("395", "Tilt Arm",                                      "BD",             "MACHINE",          "MC"),
    ("396", "Sprocket Problem",                              "BD",             "MACHINE",          "MC"),
    ("397", "Swivel Arm Problem",                            "BD",             "MACHINE",          "MC"),
    ("398", "Table Guide",                                   "BD",             "MACHINE",          "MC"),
    ("399", "Pelt Problem",                                  "BD",             "MACHINE",          "MC"),
    ("400", "Plug Assist Cylinder",                          "BD",             "MACHINE",          "MC"),
    ("401", "Puncher Problem",                               "BD",             "MACHINE",          "MC"),
    ("402", "Push Problem (Mis-Align)",                      "BD",             "MACHINE",          "MC"),
    ("403", "Ejector Push Problem",                          "BD",             "MACHINE",          "MC"),
    ("404", "Material Sag (Method)",                         "PROD-DT",        "METHOD",           "MC"),
    ("405", "SL1/SL2 Malfunction",                          "BD",             "MACHINE",          "MC"),
    ("406", "Tension Spring",                                "BD",             "MACHINE",          "MC"),
    ("407", "Air Poppet",                                    "BD",             "MACHINE",          "MC"),
    ("408", "Barrel Problem",                                "BD",             "MACHINE",          "MC"),
    ("409", "Clamping Problem",                              "BD",             "MACHINE",          "MC"),
    ("410", "Material Clog",                                 "BD",             "MACHINE",          "MC"),
    ("411", "Coil Heater",                                   "BD",             "MACHINE",          "MC"),
    ("412", "Fittings Problem",                              "BD",             "MACHINE",          "MC"),
    ("413", "Short Shot Problem",                            "PROD-DT",        "METHOD",           "MC"),
    ("415", "Pressure Pad",                                  "BD",             "MACHINE",          "MC"),
    ("416", "Air Regulator",                                 "BD",             "MACHINE",          "MC"),
    ("417", "Product Change Over - Change Setting",          "PROD-DT",        "METHOD",           "MC"),
    ("418", "Product Change Over - Set Up Change",           "PROD-DT",        "METHOD",           "MC"),
    ("419", "Product Change Over - Change Material",         "PROD-DT",        "METHOD",           "MC"),
    ("420", "Product Change Over - Change/Repair Mold (1)", "PROD-DT",        "METHOD",           "MC"),
    ("421", "Product Change Over - Change/Repair Mold (2)", "PROD-DT",        "METHOD",           "MC"),
    ("422", "Product Change Over - Eggtray",                 "PROD-DT",        "METHOD",           "MC"),
    ("423", "Product Change Over - Change Size",             "PROD-DT",        "METHOD",           "MC"),
    ("424", "Product Change Over - Making Sample",           "PROD-DT",        "METHOD",           "MC"),
    ("425", "SOP's - Start Up",                              "PROD-DT",        "METHOD",           "MC"),
    ("426", "SOP's - End of the Week",                       "PROD-DT",        "METHOD",           "MC"),
    ("427", "Mixing Ink",                                    "PROD-DT",        "METHOD",           "MC"),
    ("428", "Installation of Air Pistol",                    "PROD-DT",        "METHOD",           "MC"),
    ("429", "Decals Adjustment",                             "BD",             "MACHINE",          "QC"),
    ("430", "Robot Repair",                                  "BD",             "MACHINE",          "QC"),
    ("435", "Mold Epoxy Application / Sanding",              "PROD-DT",        "MOULD",            "QC"),
    ("436", "Demoulding Problem - Machine",                  "BD",             "MACHINE",          "QC"),
    ("437", "Demoulding Problem - Method",                   "PROD-DT",        "METHOD",           "QC"),
    ("438", "Deviated Cycle Time",                           "PROD-DT",        "METHOD",           "QC"),
    ("439", "WIP Depletion",                                 "BD",             "METHOD",           "QC"),
    ("440", "Parameter Adjustment - Production",             "BD",             "METHOD",           "QC"),
    ("441", "Unattainable SOPH - For IE Validation",         "BD",             "METHOD",           "QC"),
    ("442", "Roll Quality Problem",                          "PROD-DT",        "METHOD",           "QC"),
    ("443", "Balance Valve Problem",                         "PROD-DT",        "MACHINE",          "QC"),
    ("444", "Material Hopper Problem",                       "BD",             "MACHINE",          "QC"),
    ("445", "Mould Clamp Retightening / Repair",             "BD",             "MOULD",            "QC"),
    ("446", "Drain M1/M2 Malfunction",                       "BD",             "MACHINE",          "QC"),
    ("447", "Steam M1/M2 Malfunction",                       "BD",             "MACHINE",          "QC"),
    ("448", "Product Guide / Guide Post Alignment",          "BD",             "MOULD",            "QC"),
    ("449", "No Available Product to Cut",                   "PROD-DT",        "METHOD",           "QC"),
    ("450", "Cutter Setting",                                "PROD-DT",        "METHOD",           "QC"),
    ("451", "No Available Roll",                             "PROD-DT",        "METHOD",           "QC"),
    ("452", "Consume Roll",                                  "PROD-DT",        "METHOD",           "QC"),
    ("453", "Machine Setting",                               "PROD-DT",        "METHOD",           "QC"),
]


def _insert_records():
    existing_codes = set(
        frappe.get_all(
            "Downtime Reason",
            filters={"name": ["in", [record[0] for record in RECORDS]]},
            pluck="name",
        )
    )
    now = frappe.utils.now_datetime()
    user = frappe.session.user or "Administrator"
    fields = [
        "name",
        "owner",
        "creation",
        "modified",
        "modified_by",
        "docstatus",
        "idx",
        "dt_code",
        "description",
        "category",
        "subcategory",
        "plant",
        "is_active",
    ]
    values = [
        (
            dt_code,
            user,
            now,
            now,
            user,
            0,
            0,
            dt_code,
            description,
            category,
            subcategory,
            plant,
            1,
        )
        for dt_code, description, category, subcategory, plant in RECORDS
        if dt_code not in existing_codes
    ]

    if values:
        frappe.db.bulk_insert(
            "Downtime Reason",
            fields=fields,
            values=values,
            ignore_duplicates=True,
        )

    print(f"Inserted: {len(values)}  |  Skipped (already exist): {len(existing_codes)}")
